# Generated by Django 5.0.6 on 2024-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("descricao", models.CharField(max_length=400)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
